import type {Metadata} from "next";
import "@/style/globals.css";


export const metadata: Metadata = {
    title: "Hex Converter",
    description: "Generated by Lieval",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="id">
            <body>
                {children}
            </body>
        </html>
    );
}


